backend:
  name: git-gateway
  branch: develop # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
site_url: https://heyashu.in
logo_url: https://avatars.githubusercontent.com/u/40313523?v=4

media_folder: public/images/blogs
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    description: 🌱 Feel free to contribute! Write a new blog or edit an existing one if you spot any errors. As soon as you submit your changes, a pull request will be created. Once it’s merged, your update will go live on heyashu.in/blog/[your-blog-title] within minutes! 🚀 Let's grow this digital garden together! 🌿✨
    folder: "/src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "" # Filename template, e.g., YYYY-MM-DD-title.md
    delete: false
    fields: # The fields for each document, usually in front matter
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: 'This will render on the top of the page as heading and will be used as slug',
           pattern: ['.{10,}', "Must have at least 10 characters"]
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          time_format: false,
          date_format: "DD-MM-YYYY",
          format: "DD-MM-YYYY",
        }
      - {
          label: "Blog Thumbnail Image",
          required: false,
          name: "thumbnail",
          widget: "image",
          hint: 'This will appear on the top of the blog after title.',
        }
      - { label: "Author", name: "author", widget: "string" }
      - {
          label: "Profile Picture URL",
          name: "profilePic",
          widget: "image",
          hint: 'This image will be shown in the profile picture  avatar.',
        }
      - {
          label: "Follow Link ( When user clicks on follow button)",
          name: "followLink",
          widget: "string",
        }
      - {
          label: "Meta Info : Name",
          name: "metaName",
          required: false,
          widget: "string",
        }
      - {
          label: "Meta Content : Name",
          name: "metaContent",
          required: false,
          widget: "string",
        }
      - {
          label: "Describe your content here",
          name: "body",
          widget: "markdown",
        }
    preview_fields: ["title", "body"]
    preview_template: "blog-post"

preview_styles: ["https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"]
preview_templates:
  blog-post: |
    <div class="max-w-3xl mx-auto p-6">
      <h1 class="text-3xl font-bold mb-4">{{title}}</h1>
      <div class="prose">{{body}}</div>
    </div>
